In [35]:
import pandas as pd

df = pd.read_csv('CleaningV2.txt', header = 0)
df = pd.read_csv('CleaningV2.txt', names = ['#YY'  ,'MM' ,'DD' ,'hh' ,'mm' ,
'WDIR' ,'WSPD', 'GST' , 'WVHT',  'DPD' ,  'APD' , 'MWD' ,  'PRES' , 'ATMP' , 'WTMP' , 'DEWP' , 'VIS' , 'TIDE'])
# Imports the text file and sets up the column names
df = df.drop(df.index[0:2])
df=df.reset_index(drop=True)
#got rid of useless rows and reset the index back to 0

df= df.astype(float)
#changes all the data to float

df = df[(df.hh >= 6) & (df.hh <= 17)]
df=df.reset_index(drop=True)
#only grabs the hours between 6am - 6pm
df = df[df != 99]
df = df[df!= 999]
df = df.fillna(0)
# removing useless values and replaces them with 0

df = df.groupby(df.index // 36).mean()




df

,#YY,MM,DD,hh,mm,WDIR,WSPD,GST,WVHT,DPD,APD,MWD,PRES,ATMP,WTMP,DEWP,VIS,TIDE
0,2021.0,1.0,1.0,8.5,25.0,331.944444,8.197222,10.141667,0.115278,0.492778,0.494722,46.916667,1031.002778,2.350000,7.300000,-3.922222,0.0,0.0
1,2021.0,1.0,1.0,14.5,25.0,324.027778,3.180556,4.466667,0.088889,1.043056,0.646111,36.111111,1033.205556,1.394444,7.311111,-4.272222,0.0,0.0
2,2021.0,1.0,2.0,8.5,25.0,91.416667,8.833333,10.958333,0.164167,0.689167,0.636944,19.333333,1013.738889,5.941667,7.300000,4.805556,0.0,0.0
3,2021.0,1.0,2.0,14.5,25.0,216.333333,8.288889,10.886111,0.260000,1.025278,0.783889,17.138889,1002.988889,6.377778,7.272222,5.666667,0.0,0.0
4,2021.0,1.0,3.0,8.5,25.0,223.611111,5.888889,7.933333,0.292500,1.451667,0.983611,10.861111,1021.400000,1.958333,7.100000,-1.288889,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,2021.0,1.0,29.0,14.5,25.0,311.694444,12.341667,16.233333,0.277500,0.828611,0.725000,51.777778,1012.127778,-10.036111,5.044444,-13.216667,0.0,0.0
58,2021.0,1.0,30.0,8.5,25.0,319.666667,9.344444,12.469444,0.333611,1.266667,0.839722,9.194444,1021.683333,-9.330556,4.900000,-12.505556,0.0,0.0
59,2021.0,1.0,30.0,14.5,25.0,319.055556,7.430556,10.336111,0.353056,1.744722,1.069167,13.555556,1023.619444,-9.625000,4.891667,-13.694444,0.0,0.0
60,2021.0,1.0,31.0,8.5,25.0,323.694444,6.083333,8.272222,0.309444,2.032500,1.186389,13.277778,1027.041667,-8.436111,4.750000,-11.177778,0.0,0.0
61,2021.0,1.0,31.0,14.5,25.0,292.277778,2.555556,4.480556,0.251667,1.946389,1.237778,12.222222,1028.136111,-7.208333,4.838889,-10.994444,0.0,0.0